# suppress inspection "UnusedProperty" for whole file
logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.org.apache.http=DEBUG
#logging.level.httpclient.wire=DEBUG
shareit-server.url=http://localhost:9090
server.port=8080

# Solve the weird connection close error inbetween comment tests. This way Postman will know to expect a closed conn.
server.tomcat.keep-alive-timeout=1000